services:
  frontend:
    build: 
      context: ./rsa-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://backend
      - VITE_API_BASE_PORT=8080
  backend:
    build:
      context: ./rsa-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_API_PORT=8080
